# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 06:28
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_categories', '0003_auto_20170622_0941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(False, 'Individual'), (True, 'Business')], default=True)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, choices=[('BH', 'Bahrain'), ('EG', 'Egypt'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('OM', 'Oman'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates')], max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address', models.TextField(blank=True, max_length=255, null=True)),
                ('hq_country', models.CharField(blank=True, max_length=255, null=True)),
                ('hq_city', models.CharField(blank=True, max_length=255, null=True)),
                ('hq_address', models.CharField(blank=True, max_length=255, null=True)),
                ('hq_contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('brief_desc', models.TextField(blank=True, max_length=255, null=True)),
                ('pri_det_status', models.IntegerField(default=0)),
                ('sec_det_status', models.IntegerField(default=0)),
                ('primary_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=accounts.models.get_upload_img_business)),
                ('business_sub_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_bsubcategory', to='business_categories.BSubCategory')),
                ('business_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_bcategory', to='business_categories.BCategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Users',
                'verbose_name_plural': 'Business Users',
            },
        ),
        migrations.CreateModel(
            name='IndividualAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(False, 'Individual'), (True, 'Business')], default=False)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, choices=[('BH', 'Bahrain'), ('EG', 'Egypt'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('OM', 'Oman'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates')], max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.BooleanField(choices=[(False, 'Male'), (True, 'Female')], default=False)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Hide Personal Details')),
                ('contact_status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Hide Contact Details')),
                ('profile_img', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=accounts.models.get_upload_img_individual)),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=accounts.models.get_upload_img_individual)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Users',
                'verbose_name_plural': 'Individual Users',
            },
        ),
    ]
