# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='business_sub_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_bsubcategory', to='business_categories.BSubCategory'),
        ),
    ]
