# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20170622_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfeatures',
            name='rand_id',
        ),
        migrations.RemoveField(
            model_name='adfeatures',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='adfeatures',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='rand_id',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='adimage',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='rand_id',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='sub_cat_id',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='sub_type_id',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='adname',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='adpricing',
            name='rand_id',
        ),
        migrations.RemoveField(
            model_name='adpricing',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='adpricing',
            name='usertype',
        ),
        migrations.AddField(
            model_name='adfeatures',
            name='adname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adname_feature', to='home.AdName'),
        ),
        migrations.AddField(
            model_name='adname',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adname_category', to='classified_categories.Category'),
        ),
        migrations.AddField(
            model_name='adname',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adname_subcategory', to='classified_categories.SubCategory'),
        ),
        migrations.AddField(
            model_name='adname',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adname_scategorytype', to='classified_categories.SubCategoryType'),
        ),
        migrations.AddField(
            model_name='adname',
            name='type',
            field=models.BooleanField(choices=[(False, 'Classified'), (True, 'Business')], default=False),
        ),
        migrations.AddField(
            model_name='adname',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adname_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adpricing',
            name='adname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adname_pricing', to='home.AdName'),
        ),
        migrations.AlterField(
            model_name='adfeatures',
            name='condition_of_item',
            field=models.CharField(blank=True, choices=[('', 'Condition of Items'), ('Brand New Still in Packing', 'Brand New Still in Packing'), ('New without original packing', 'New without original packing'), ('Sparingly used', 'Sparingly used'), ('Used', 'Used'), ('Canadians', 'Canadians'), ('In good condition', 'In good condition'), ('Used with a few notable damage', 'Used with a few notable damage'), ('Needs Repair', 'Needs Repair')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adfeatures',
            name='period_used',
            field=models.CharField(blank=True, choices=[('', 'Period Used'), ('Not Used', 'Not Used'), ('Few Days', 'Few Days'), ('1 Month', '1 Month'), ('2-6 months', '2-6 months'), ('6-12 months', '6-12 months'), ('above 12 months', 'above 12 months'), ('1 to 2 years used', '1 to 2 years used'), ('used above 2 years', 'used above 2 years')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adfeatures',
            name='warranty',
            field=models.CharField(blank=True, choices=[('', 'Warranty'), ('Full Warranty Available', 'Full Warranty Available'), ('No Warranty', 'No Warranty'), ('Does not Apply', 'Does not Apply')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adfeaturespricing',
            name='ad_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_price', to='home.AdFeatures'),
        ),
        migrations.AlterField(
            model_name='adfeaturespricing',
            name='delivery_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adfeaturespricing',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='adname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adimages', to='home.AdName'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=home.models.get_upload_img_adname),
        ),
        migrations.AlterField(
            model_name='adname',
            name='ad_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adname',
            name='ad_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adname',
            name='ad_type',
            field=models.BooleanField(choices=[(False, 'Products'), (True, 'Services')], default=False),
        ),
        migrations.AlterField(
            model_name='adpricing',
            name='ad_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adpricing',
            name='ad_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adpricing',
            name='ad_push_to_top',
            field=models.BooleanField(default=False),
        ),
    ]
