# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170706_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfeaturespricing',
            name='counter',
        ),
    ]
