# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_adfeaturespricing_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adname',
            name='ad_complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adname',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adname_subcategory', to='classified_categories.SubCategory'),
        ),
    ]
